"""
Base models for the Autonomous Software Development Agent.
"""
from pydantic import BaseModel, Field
from typing import List, Dict, Optional, Any, Union


class Requirement(BaseModel):
    """
    Represents a natural language requirement for software development.
    """
    id: str
    description: str
    priority: str = "medium"
    tags: List[str] = Field(default_factory=list)
    dependencies: List[str] = Field(default_factory=list)
    

class TechnicalTask(BaseModel):
    """
    Represents a technical task derived from requirements.
    """
    id: str
    title: str
    description: str
    requirement_ids: List[str]
    estimated_complexity: str = "medium"
    status: str = "pending"
    dependencies: List[str] = Field(default_factory=list)


class CodeSnippet(BaseModel):
    """
    Represents a code snippet generated by the coding agent.
    """
    id: str
    task_id: str
    code: str
    language: str
    file_path: Optional[str] = None
    description: str = ""
    

class TestCase(BaseModel):
    """
    Represents a test case for code validation.
    """
    id: str
    title: str
    description: str
    code_snippet_ids: List[str]
    test_code: str
    expected_result: str
    status: str = "pending"
    

class Issue(BaseModel):
    """
    Represents an issue identified during testing or debugging.
    """
    id: str
    title: str
    description: str
    code_snippet_ids: List[str]
    severity: str = "medium"
    status: str = "open"
    

class TestExecutionResult(BaseModel):
    """
    Represents the result of executing a test case.
    """
    test_id: str
    passed: bool
    output: str
    error_message: Optional[str] = None


class Documentation(BaseModel):
    """
    Represents documentation for code or features.
    """
    id: str
    title: str
    content: str
    code_snippet_ids: List[str]
    doc_type: str = "technical"  # technical, user, api
    

class Feedback(BaseModel):
    """
    Represents user feedback for the agent's output.
    """
    id: str
    content: str
    target_id: str  # ID of the entity receiving feedback
    target_type: str  # Type of entity (code, test, documentation)
    rating: Optional[float] = None  # Optional numerical rating
    

class AgentState(BaseModel):
    """
    Represents the current state of an agent in the system.
    """
    agent_id: str
    agent_type: str
    status: str = "idle"  # idle, working, waiting, error
    current_task_id: Optional[str] = None
    memory: Dict[str, Any] = Field(default_factory=dict)
    

class WorkflowState(BaseModel):
    """
    Represents the current state of the entire workflow.
    """
    workflow_id: str
    status: str = "in_progress"
    current_step: str
    requirements: List[Requirement] = Field(default_factory=list)
    technical_tasks: List[TechnicalTask] = Field(default_factory=list)
    code_snippets: List[CodeSnippet] = Field(default_factory=list)
    test_cases: List[TestCase] = Field(default_factory=list)
    issues: List[Issue] = Field(default_factory=list)
    documentation: List[Documentation] = Field(default_factory=list)
    feedback: List[Feedback] = Field(default_factory=list)
    agent_states: Dict[str, AgentState] = Field(default_factory=dict)
